server:
  port: 8191
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/dulminkannangara/microservices-course-krish-config-store
          search-paths:
            - 'serviceconfig'
#          repos:
#            appstage:
#              pattern: app-stage
#              uri: https://github.com/dulminkannangara/spring-cloud-config-store2



#          username: username of the private repository
#          password: 1234