
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/taskDB?createDatabaseIfNotExist=true
    username: root
    password: 1234
    driver-class-name: com.mysql.jdbc.Driver
  application:
    name: task