server:
  port: 8191
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/dulminkannangara/spring-cloud-config-store
          search-paths:
            - '*service'
          repos:
            appstage:
              pattern: app-stage
              uri: https://github.com/dulminkannangara/spring-cloud-config-store2



#          username: username of the private repository
#          password: 1234